version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-blog_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-blog_password}
      POSTGRES_DB: ${DB_NAME:-blog_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - blog_network

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - minio_data:/data
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    networks:
      - blog_network

  # Blog API
  blog-api:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${DB_USER:-blog_user}:${DB_PASSWORD:-blog_password}@postgres:5432/${DB_NAME:-blog_db}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
      PORT: 3000
      NODE_ENV: production
    ports:
      - "${API_PORT:-3000}:3000"
    depends_on:
      - postgres
      - minio
    networks:
      - blog_network
    volumes:
      - ./logs:/usr/src/app/logs

volumes:
  postgres_data:
  minio_data:

networks:
  blog_network:
    driver: bridge